### ISSUE TITLE
Indexing on the fly

### ISSUE THREAD

**Issue by mha1** [offer-shmuely/edgetx-x10-scripts#6]
Hi Offer,

Great tool! Just a suggestion as indexing takes a long time and is repeated at every start: Wouldn't it be more efficient to just index the log file at the instant when it is selected? Especially with even a few longer logs written at higher frequencies the wait is too long.

Regards,
Michael

**Comment by offer-shmuely** [comment]
well, I tried it this way, it save the long waiting time, that's true.
however, you get other issues instead
1. there is a delay after you select the file, and going ahead to selecting the sensors, and that delay will happen again and again since it can not be cached.
2. the list of the files is a lot longer, since we can not filter too shot files (edgeTx does verify that the log have minimal data in it)
you see files that do have a lot of time in them, but the data is not changed, it happen when you turn on the radio, with your log switch on, and the model is not connected.
3. the list of the columns to select into each of the 4 sensors, is match longer, since I can not automatically filter the columns that have not data, like many of the switch's (SA, SB, SC, SE, ...)


what I do instead, is index once each file, yes it take about 2-3sec per file, but the file is not index again, and later we can smart stuff like the above, and match faster, while cleaning some of the non usable data.

my suggestion is:
1. clean once the old logs, and start over
2. let it run at home once, it will take time. but then when you need it, it will be relatively fast (at least if you fly like me about 10 long flight a week)

Hope I helped

**Comment by ParkerEde** [comment]
Hi Offer,
great tool. Thank you very much.
The waiting time at startup is indeed very long, especially if the last indexing step was a long time ago. What do you think about indexing only the log files of the currently active model at startup?
Kind regards

**Comment by offer-shmuely** [comment]
I am working on an update like this for john (rcvideoreview) request
Please wait a week or two
When it ready, it will be here, on this repo
